### ISSUE TITLE
Non-optional `Package::arch` ?

### ISSUE THREAD

**Issue by fosskers** [Morganamilo/alpm.rs#15]
I noticed that `Package::arch` returns in `Option`:
```rust
    pub fn arch(&self) -> Option<&'a str> {
        let arch = unsafe { alpm_pkg_get_arch(self.pkg) };
        unsafe { from_cstr_optional(arch) }
    }
```

Yet `alpm` itself seems total:
```c
/** Returns the architecture for which the package was built.
 * @param pkg a pointer to package
 * @return a reference to an internal string
 */
const char *alpm_pkg_get_arch(alpm_pkg_t *pkg);
```
which has the exact same structure as `name`:
```c
const char *alpm_pkg_get_name(alpm_pkg_t *pkg);
```
which is a total function in the Rust. Could the Rust also return a plain `&'a str` for `arch()`?

**Comment by Morganamilo** [comment]
Only name and version are actually required. Everything may not actually exist. Docs will get there eventually.

**Comment by fosskers** [comment]
When it doesn't actually exist, what happens when `alpm_pkg_get_name` is called? Do you get a null pointer?

**Comment by Morganamilo** [comment]
Yep.

**Comment by Morganamilo** [comment]
If you do plan to fix the docs. For the love of god pleas hold of until my huge patch set is merged. Rebasing not fun.

**Comment by fosskers** [comment]
No problem. I had a few other docs-related things I want to do in the `pacman` repo, but yeah I'm going to wait.
