### ISSUE TITLE
Alpm does not implement Send

### ISSUE THREAD

**Issue by Bluskript** [Morganamilo/alpm.rs#6]
It doesn't seem to be possible to use Alpm in threads safely, due to the presence of `*mut alpm_handle_t` in the struct. Is there a good reason for this, or is it maybe possible to refactor code to make it work in concurrent contexts?

**Comment by Morganamilo** [comment]
I just didn't need it and didn't want to implement it without making sure it was safe. Off the top of my head I don't see why Alpm couldn't be Send.
